/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlotterRouteImport } from './routes/blotter'
import { Route as MarketTickerRouteImport } from './routes/market.$ticker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlotterRoute = BlotterRouteImport.update({
  id: '/blotter',
  path: '/blotter',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketTickerRoute = MarketTickerRouteImport.update({
  id: '/market/$ticker',
  path: '/market/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blotter': typeof BlotterRoute
  '/market/$ticker': typeof MarketTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blotter': typeof BlotterRoute
  '/market/$ticker': typeof MarketTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blotter': typeof BlotterRoute
  '/market/$ticker': typeof MarketTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blotter' | '/market/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blotter' | '/market/$ticker'
  id: '__root__' | '/' | '/blotter' | '/market/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlotterRoute: typeof BlotterRoute
  MarketTickerRoute: typeof MarketTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blotter': {
      id: '/blotter'
      path: '/blotter'
      fullPath: '/blotter'
      preLoaderRoute: typeof BlotterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$ticker': {
      id: '/market/$ticker'
      path: '/market/$ticker'
      fullPath: '/market/$ticker'
      preLoaderRoute: typeof MarketTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlotterRoute: BlotterRoute,
  MarketTickerRoute: MarketTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
